name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: |
          rustup update stable
          cargo build --verbose
      - name: Run tests
        run: cargo test --features large_thread --verbose --all
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  test-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: |
          rustup update stable
          cargo build --verbose
      - name: Run tests
        # HACK: The cause is unknown, but on windows, the exit code is 1 even if tests are successful.
        run: cargo test --features large_thread --features pre-commit --verbose --all
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
